[package]
name = "route53-util"
version = "0.2.0"
authors = ["Adam Batkin <adam@batkin.net>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
structopt = "0.3"
anyhow = "1"
aws-config = "0.55"
aws-sdk-route53 = "0.26.0"
tokio = { version = "1", features = ["full"] }
